/**
 * Unified Blog Engine — SPA, config-driven, zero-build.
 * Architecture: Config → State → DataLoader → Renderer → UI → Router
 *
 * ─────────────────────────────────────────────────────────────────
 *  USAGE
 *  Load a brand config BEFORE this file in your HTML:
 *    <script src="/config-verteil.js"></script>   <!-- or config-shani.js etc. -->
 *    <script src="/script.js"></script>
 *
 *  To add a new brand, copy config-verteil.js, rename it, and fill
 *  in the values. Do NOT edit this file for branding.
 * ─────────────────────────────────────────────────────────────────
 */

if (typeof CONFIG === 'undefined') {
  throw new Error('[Blog Engine] No CONFIG found. Load a brand config script before script.js.');
}

// ── Tag icons using Font Awesome ──────────────────────────────
const TAG_ICONS = {
  Product:      'fa-solid fa-box-open',
  Engineering:  'fa-solid fa-gears',
  News:         'fa-solid fa-newspaper',
  Release:      'fa-solid fa-rocket',
  Careers:      'fa-solid fa-briefcase',
  Culture:      'fa-solid fa-people-group',
  Partnerships: 'fa-solid fa-handshake',
  Linux:        'fa-brands fa-linux',
  NDC:          'fa-solid fa-plane',
  AWS:          'fa-brands fa-aws',
  DevOps:       'fa-solid fa-gears',
  Platform:     'fa-solid fa-layer-group',
  Incident:     'fa-solid fa-triangle-exclamation',
  Essay:        'fa-solid fa-feather-pointed',
  Post:         'fa-solid fa-file-lines',
};

// =========================================
// 1. STATE
// =========================================
const AppState = {
  posts: [],
  postsCache: {},
  filter: 'all',
  search: '',
  theme: localStorage.getItem('blogs-theme') || (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'),
  isMember: localStorage.getItem('blogs_member') === '1',
  pagination: { page: 1, perPage: 9 }
};

// ── Validate stored license key silently on page load ─────────
(async function validateStoredLicense() {
  const stored = localStorage.getItem('blogs_license');
  if (!stored || !CONFIG.LEMONSQUEEZY_STORE) return;

  // Decode stored key — atob() throws on corrupt/non-base64 data; treat that as invalid.
  let key;
  try { key = atob(stored); } catch {
    localStorage.removeItem('blogs_member');
    localStorage.removeItem('blogs_license');
    AppState.isMember = false;
    return;
  }

  try {
    const res = await fetch('https://api.lemonsqueezy.com/v1/licenses/validate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ license_key: key })
    });
    const data = await res.json();
    if (!data.valid) {
      localStorage.removeItem('blogs_member');
      localStorage.removeItem('blogs_license');
      AppState.isMember = false;
    }
  } catch { /* network error — leave membership state as-is */ }
})();

// =========================================
// 2. UTILS
// =========================================
const Utils = {
  qs: (sel, root) => (root || document).querySelector(sel),
  escapeHtml: str => String(str)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;'),
  // safeText — use for text nodes rendered via innerHTML (NOT attributes).
  // Only escapes & < > so apostrophes and quotes display correctly.
  safeText: str => String(str)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'),
  fmtDate: str => {
    const d = new Date(str + 'T00:00:00');
    return isNaN(d) ? str : d.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  },
  fmtDateShort: str => {
    const d = new Date(str + 'T00:00:00');
    return isNaN(d) ? str : d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  },
  tagIcon: tag => `<i class="${TAG_ICONS[tag] || TAG_ICONS.Post}" aria-hidden="true"></i>`,
  parseFrontmatter: raw => {
    const md = raw.replace(/^\uFEFF/, '');
    const match = md.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
    if (!match) return { fm: {}, body: md };
    const fm = {};
    match[1].split(/\r?\n/).forEach(line => {
      const i = line.indexOf(':');
      if (i < 1) return;
      fm[line.slice(0, i).trim()] = line.slice(i + 1).trim().replace(/^['"`]|['"`]$/g, '');
    });
    return { fm, body: match[2] };
  },
  slugify: text => text.toLowerCase()
    .replace(/[^\w\s-]/g, '').trim()
    .replace(/[\s_]+/g, '-').replace(/-+/g, '-'),
  CALLOUT_TYPES: {
    NOTE:      { icon: 'fa-solid fa-circle-info',          cls: 'callout-note'      },
    TIP:       { icon: 'fa-solid fa-lightbulb',            cls: 'callout-tip'       },
    WARNING:   { icon: 'fa-solid fa-triangle-exclamation', cls: 'callout-warning'   },
    CAUTION:   { icon: 'fa-solid fa-fire',                 cls: 'callout-caution'   },
    IMPORTANT: { icon: 'fa-solid fa-star',                 cls: 'callout-important' },
  },
  renderMath(html) {
    if (typeof katex === 'undefined') return html;
    const parts = html.split(/(<pre[\s\S]*?<\/pre>|<code[\s\S]*?<\/code>)/);
    return parts.map((part, i) => {
      if (i % 2 === 1) return part;
      part = part.replace(/\$\$([\s\S]+?)\$\$/g, (_, expr) => {
        try { return katex.renderToString(expr.trim(), { displayMode: true, throwOnError: false }); }
        catch { return ''; }
      });
      part = part.replace(/(?<!\$)\$([^\n$]+?)\$(?!\$)/g, (_, expr) => {
        try { return katex.renderToString(expr.trim(), { displayMode: false, throwOnError: false }); }
        catch { return ''; }
      });
      return part;
    }).join('');
  },
  // ─── MEDIA SHORTCODES ─────────────────────────────────────────
  _mediaBlocks: {},
  _mediaToken(html) {
    const key = `MBLOCK_${Object.keys(Utils._mediaBlocks).length}_END`;
    Utils._mediaBlocks[key] = html;
    return '\n\n' + key + '\n\n';
  },
  _cap: raw => {
    const pipe = raw.lastIndexOf('|');
    return pipe === -1
      ? { val: raw.trim(), caption: '' }
      : { val: raw.slice(0, pipe).trim(), caption: raw.slice(pipe + 1).trim() };
  },
  _youtube(id, caption) {
    const fig = caption ? `<figcaption>${caption}</figcaption>` : '';
    return `<figure class="media-embed"><div class="media-embed__ratio"><iframe src="https://www.youtube-nocookie.com/embed/${id}" title="${caption || 'YouTube video'}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>${fig}</figure>`;
  },
  _vimeo(id, caption) {
    const fig = caption ? `<figcaption>${caption}</figcaption>` : '';
    return `<figure class="media-embed"><div class="media-embed__ratio"><iframe src="https://player.vimeo.com/video/${id}?dnt=1" title="${caption || 'Vimeo video'}" loading="lazy" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe></div>${fig}</figure>`;
  },
  _video(src, caption) {
    const fig  = caption ? `<figcaption>${caption}</figcaption>` : '';
    const ext  = src.split('?')[0].split('.').pop().toLowerCase();
    const mime = { mp4: 'video/mp4', webm: 'video/webm', ogg: 'video/ogg', mov: 'video/mp4' }[ext] || 'video/mp4';
    return `<figure class="media-figure media-figure--video"><video controls preload="metadata" playsinline loading="lazy"><source src="${src}" type="${mime}">Your browser doesn't support HTML video. <a href="${src}">Download it</a>.</video>${fig}</figure>`;
  },
  _audio(src, caption) {
    const fig = caption ? `<figcaption>${caption}</figcaption>` : '';
    return `<figure class="media-figure media-figure--audio"><audio controls preload="metadata" loading="lazy"><source src="${src}">Your browser doesn't support HTML audio. <a href="${src}">Download it</a>.</audio>${fig}</figure>`;
  },
  _image(src, rest) {
    const parts   = rest.split('|').map(s => s.trim());
    const alt     = parts[0] || '';
    const caption = parts[1] !== undefined ? parts[1] : alt;
    const wide    = parts[2] === 'wide';
    const fig     = caption ? `<figcaption>${caption}</figcaption>` : '';
    return `<figure class="media-figure${wide ? ' media-figure--wide' : ''}"><img src="${src}" alt="${alt}" loading="lazy">${fig}</figure>`;
  },
  // ─── Strip manual TOC block from raw markdown (for preview counting) ───
  _stripTocBlock(text) {
    return text
      .replace(/^#{1,3}\s+(?:table\s+of\s+)?contents?\s*\n[\s\S]*?(?=\n(?=#{1,3}\s))/im, '')
      .replace(/^\[\[?toc\]?\]\s*$/im, '')
      .trim();
  },

  // ─── TABLE OF CONTENTS ────────────────────────────────────────
  _buildToc(text) {
    // Extract h2/h3 headings (h1 is the post title, skip it)
    const headings = [];
    const re = /^(#{2,3})\s+(.+)$/gm;
    let m;
    while ((m = re.exec(text)) !== null) {
      const level = m[1].length;
      const raw   = m[2].replace(/\*+|`|_+/g, '').trim();
      // Skip the TOC heading itself
      if (/^(?:table\s+of\s+)?contents?$/i.test(raw)) continue;
      const id    = Utils.slugify(raw);
      headings.push({ level, text: raw, id });
    }
    if (headings.length < 2) return '';
    let html = '<nav class="toc" aria-label="Table of contents"><p class="toc__title"><i class="fa-solid fa-list-ul" aria-hidden="true"></i> Contents</p><ol class="toc__list">';
    let inSub = false;
    headings.forEach((h, i) => {
      if (h.level === 2) {
        if (inSub) { html += '</li></ol></li>'; inSub = false; }
        else if (i > 0) html += '</li>';
        html += `<li class="toc__item"><a href="#${h.id}">${h.text}</a>`;
      } else {
        if (!inSub) { html += '<ol class="toc__sub">'; inSub = true; }
        else html += '</li>';
        html += `<li class="toc__item toc__item--sub"><a href="#${h.id}">${h.text}</a>`;
      }
    });
    if (inSub) html += '</li></ol></li>';
    else html += '</li>';
    html += '</ol></nav>';
    return html;
  },

  _processShortcodes(text) {
    Utils._mediaBlocks = {};
    // ── [toc] / [[toc]] shortcode ─────────────────────────────
    if (/\[\[?toc\]?\]/i.test(text)) {
      const tocHtml = Utils._buildToc(text);
      text = text.replace(/\[\[?toc\]?\]/gi, tocHtml ? Utils._mediaToken(tocHtml) : '');
    }
    // ── Auto-detect manual "## Table of Contents" block ───────
    // Matches: optional h2/h3 heading containing "table of contents" / "contents"
    // followed by a markdown list of links — strips it and replaces with styled TOC
    text = text.replace(
      /^#{1,3}\s+(?:table\s+of\s+)?contents?\s*\n[\s\S]*?(?=\n(?=#{1,3}\s))/im,
      (match) => {
        const tocHtml = Utils._buildToc(text);
        return tocHtml ? Utils._mediaToken(tocHtml) : '';
      }
    );
    text = text.replace(/::youtube\[([^\]]+)\]/g, (_, raw) => {
      const { val, caption } = Utils._cap(raw);
      return Utils._mediaToken(Utils._youtube(val, caption));
    });
    text = text.replace(/::vimeo\[([^\]]+)\]/g, (_, raw) => {
      const { val, caption } = Utils._cap(raw);
      return Utils._mediaToken(Utils._vimeo(val, caption));
    });
    text = text.replace(/::video\[([^\]]+)\]/g, (_, raw) => {
      const { val, caption } = Utils._cap(raw);
      return Utils._mediaToken(Utils._video(val, caption));
    });
    text = text.replace(/::audio\[([^\]]+)\]/g, (_, raw) => {
      const { val, caption } = Utils._cap(raw);
      return Utils._mediaToken(Utils._audio(val, caption));
    });
    text = text.replace(/::image\[([^\]]+)\]/g, (_, raw) => {
      const first = raw.indexOf('|');
      const src   = first === -1 ? raw.trim() : raw.slice(0, first).trim();
      const rest  = first === -1 ? '' : raw.slice(first + 1);
      return Utils._mediaToken(Utils._image(src, rest));
    });
    return text;
  },
  _restoreShortcodes(html) {
    html = html.replace(/<p>(MBLOCK_\d+_END)<\/p>/g, (_, token) => Utils._mediaBlocks[token] || '');
    html = html.replace(/MBLOCK_\d+_END/g, token => Utils._mediaBlocks[token] || '');
    return html;
  },
  safeMarkdown: text => {
    if (typeof marked !== 'undefined') {
      text = Utils._processShortcodes(text);
      const renderer = new marked.Renderer();

      renderer.code = (code, lang) => {
        const safeLang = (lang || '').split(/\s/)[0];
        const cls = safeLang ? `class="language-${safeLang}"` : '';
        const escaped = code
          .replace(/&/g, '&amp;')
          .replace(/</g, '&lt;')
          .replace(/>/g, '&gt;')
          .replace(/"/g, '&quot;');
        return `<pre><code ${cls}>${escaped}</code></pre>\n`;
      };

      renderer.heading = (text, level) => {
        const id = Utils.slugify(text.replace(/<[^>]+>/g, ''));
        return `<h${level} id="${id}">${text}<a class="heading-anchor" href="#${id}" aria-hidden="true">#</a></h${level}>\n`;
      };

      renderer.link = (href, title, linkText) => {
        const isExternal = href && !href.startsWith('#') && !href.startsWith('/');
        const t = title ? ` title="${title}"` : '';
        const ext = isExternal ? ` target="_blank" rel="noopener noreferrer"` : '';
        return `<a href="${href}"${t}${ext}>${linkText}</a>`;
      };

      renderer.image = (src, title, alt) => {
        const t       = title ? ` title="${title}"` : '';
        const caption = alt || title;
        const fig     = caption ? `<figcaption>${caption}</figcaption>` : '';
        return `<figure class="media-figure"><img src="${src}" alt="${alt || ''}"${t} loading="lazy">${fig}</figure>`;
      };

      renderer.blockquote = (quote) => {
        const match = quote.match(/^<p>\[!(NOTE|TIP|WARNING|CAUTION|IMPORTANT)\]([\s\S]*)/i);
        if (match) {
          const type = match[1].toUpperCase();
          const cfg  = Utils.CALLOUT_TYPES[type] || Utils.CALLOUT_TYPES.NOTE;
          const body = match[2].replace(/<\/p>$/, '').replace(/^(\s*<br\s*\/?>\s*|\n)/i, '').trim();
          return `<div class="callout ${cfg.cls}" role="note"><div class="callout__title"><i class="${cfg.icon}" aria-hidden="true"></i>${type}</div><div class="callout__body">${body}</div></div>\n`;
        }
        return `<blockquote>${quote}</blockquote>\n`;
      };

      let raw = marked.parse(text, { renderer, gfm: true, breaks: false });
      raw = Utils.renderMath(raw);

      if (typeof DOMPurify !== 'undefined') {
        raw = DOMPurify.sanitize(raw, {
          ADD_TAGS: ['pre', 'code', 'span', 'video', 'audio', 'source', 'iframe',
                     'details', 'summary', 'input', 'figure', 'figcaption',
                     'table', 'thead', 'tbody', 'tfoot', 'tr', 'th', 'td',
                     'math', 'annotation', 'semantics', 'mrow', 'mi', 'mn',
                     'mo', 'msup', 'msub', 'mfrac', 'mspace', 'mtext'],
          ADD_ATTR: ['class', 'id', 'src', 'controls', 'autoplay', 'loop', 'muted',
                     'playsinline', 'width', 'height', 'allow', 'allowfullscreen',
                     'frameborder', 'loading', 'type', 'checked', 'disabled',
                     'target', 'rel', 'title', 'alt', 'scope', 'align',
                     'encoding', 'display', 'style', 'aria-hidden', 'preload',
                     'poster', 'dnt']
        });
      }

      return Utils._restoreShortcodes(raw);
    }
    return text.replace(/\n/g, '<br>');
  },
  readTime: body => `${Math.max(1, Math.ceil(body.trim().split(/\s+/).length / 200))} min`
};

// =========================================
// 3. DATA LOADER
// =========================================
const DataLoader = {
  async load() {
    if (location.protocol === 'file:') {
      UI.showError('Open via a local server', 'Browsers block file:// fetches.', 'python3 -m http.server 8080');
      return null;
    }

    let filenames;

    if (CONFIG.GITHUB_USER && CONFIG.GITHUB_REPO) {
      // ── Auto-discover via GitHub Contents API ─────────────────
      try {
        const apiUrl = `https://api.github.com/repos/${CONFIG.GITHUB_USER}/${CONFIG.GITHUB_REPO}/contents/posts`;
        const r = await fetch(apiUrl, { headers: { 'Accept': 'application/vnd.github.v3+json' } });
        if (!r.ok) throw new Error(`GitHub API HTTP ${r.status}`);
        const entries = await r.json();
        filenames = entries
          .filter(e => e.type === 'file' && e.name.endsWith('.md') && e.name !== 'index.md')
          .map(e => e.name);
      } catch (e) {
        UI.showError('Could not list posts from GitHub API', e.message,
          `https://api.github.com/repos/${CONFIG.GITHUB_USER}/${CONFIG.GITHUB_REPO}/contents/posts`);
        return null;
      }
    } else {
      // ── Local dev fallback: posts/index.json ──────────────────
      try {
        const r = await fetch('/posts/index.json');
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        const list = await r.json();
        if (!Array.isArray(list)) throw new Error('posts/index.json must be a JSON array');
        // Fast path: metadata objects
        if (list.length > 0 && typeof list[0] === 'object' && list[0] !== null) {
          return list
            .map(item => ({
              slug:           item.slug || '',
              title:          item.title || 'Untitled',
              excerpt:        item.excerpt || '',
              date:           item.date   || new Date().toISOString().split('T')[0],
              tag:            item.tag    || 'Post',
              readTime:       item.readTime || '1 min',
              paywalled:      item.paywalled === true || item.paywalled === 'true',
              cover:          item.cover || '',
              author:         item.author         || CONFIG.AUTHOR_NAME,
              authorRole:     item.author_role    || CONFIG.AUTHOR_ROLE,
              authorBio:      item.author_bio     || CONFIG.AUTHOR_BIO,
              authorInitials: item.author_initials || CONFIG.AUTHOR_INITIALS || (
                (item.author || CONFIG.AUTHOR_NAME)
                  .split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 2)
              ),
              authorLinkedin: item.author_linkedin || '',
              authorGithub:   item.author_github   || '',
              authorWebsite:  item.author_website  || '',
            }))
            .sort((a, b) => new Date(b.date) - new Date(a.date));
        }
        filenames = list.filter(n => typeof n === 'string' && n.endsWith('.md'));
      } catch (e) {
        UI.showError('Local dev: could not load posts/index.json', e.message, '[ "my-post.md" ]');
        return null;
      }
    }

    // ── Fetch all .md files in parallel ───────────────────────
    const base = (CONFIG.GITHUB_USER && CONFIG.GITHUB_REPO)
      ? `https://raw.githubusercontent.com/${CONFIG.GITHUB_USER}/${CONFIG.GITHUB_REPO}/main/posts`
      : '/posts';

    const posts = await Promise.all(filenames.map(async name => {
      try {
        const r = await fetch(`${base}/${name}`);
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        const { fm, body } = Utils.parseFrontmatter(await r.text());
        const slug = name.replace(/\.md$/, '');
        const post = {
          slug,
          title:   fm.title || 'Untitled',
          excerpt: fm.excerpt || (() => {
            // For paywalled posts without explicit fm.excerpt, use only first paragraph
            const excerptSrc = (fm.paywalled === 'true')
              ? (body.split(/\n\n+/).find(l => l.trim() && !l.startsWith('#')) || body)
              : body;
            const s = excerptSrc
              .replace(/```[\s\S]*?```/g, '').replace(/`[^`]+`/g, '')
              .replace(/!?\[[^\]]*\]\([^)]*\)/g, '')
              .replace(/[*_~]{1,3}([^*_~]+)[*_~]{1,3}/g, '$1')
              .replace(/^#{1,6}\s+/gm, '').replace(/^>\s*/gm, '')
              .replace(/^[-*+]\s+/gm, '').replace(/\n/g, ' ').trim();
            return s.substring(0, 140) + (s.length > 140 ? '…' : '');
          })(),
          date:           fm.date     || new Date().toISOString().split('T')[0],
          tag:            fm.tag      || 'Post',
          readTime:       fm.readTime || Utils.readTime(body),
          paywalled:      fm.paywalled === 'true',
          cover:          fm.cover    || '',
          author:         fm.author         || CONFIG.AUTHOR_NAME,
          authorRole:     fm.author_role    || CONFIG.AUTHOR_ROLE,
          authorBio:      fm.author_bio     || CONFIG.AUTHOR_BIO,
          authorInitials: fm.author_initials || CONFIG.AUTHOR_INITIALS || (
            (fm.author || CONFIG.AUTHOR_NAME)
              .split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 2)
          ),
          authorLinkedin: fm.author_linkedin || '',
          authorGithub:   fm.author_github   || '',
          authorWebsite:  fm.author_website  || '',
          // For paywalled posts, keep only a short preview for non-members
          body: (fm.paywalled === 'true' && !AppState.isMember)
            ? Utils._stripTocBlock(body).split(/\n\n+/).slice(0, 12).join('\n\n')  // first ~12 paragraphs as preview
            : body,
          _previewCached: (fm.paywalled === 'true' && !AppState.isMember)
        };
        AppState.postsCache[slug] = post;
        return post;
      } catch (e) {
        console.error(`Failed: ${name}`, e);
        return null;
      }
    }));

    return posts.filter(Boolean).sort((a, b) => new Date(b.date) - new Date(a.date));
  },

  async fetchBody(slug) {
    // Return cache if: not paywalled, member with full body, or non-member with preview cached
    const cached = AppState.postsCache[slug];
    if (cached) {
      if (!cached.paywalled || AppState.isMember) return cached;
      if (cached._previewCached) return cached;
    }
    const base = (CONFIG.GITHUB_USER && CONFIG.GITHUB_REPO)
      ? `https://raw.githubusercontent.com/${CONFIG.GITHUB_USER}/${CONFIG.GITHUB_REPO}/main/posts`
      : '/posts';

    const r = await fetch(`${base}/${slug}.md`);
    if (!r.ok) throw new Error(`HTTP ${r.status} — could not load ${slug}.md`);

    const { fm, body } = Utils.parseFrontmatter(await r.text());
    const meta = AppState.posts.find(p => p.slug === slug) || {};
    const isPaywalled = fm.paywalled === 'true' || meta.paywalled;
    // Provide preview body for non-members, full body for members
    const previewBody = Utils._stripTocBlock(body).split(/\n\n+/).slice(0, 12).join('\n\n');
    const full = { ...meta, body: (isPaywalled && !AppState.isMember) ? previewBody : body, _previewCached: (isPaywalled && !AppState.isMember) };
    AppState.postsCache[slug] = full;
    return full;
  }
};

// =========================================
// 4. RENDERER
// =========================================
const Renderer = {
  // ── Inject all brand strings from CONFIG into the DOM ────────
  applyBranding() {
    const fullTitle = `${CONFIG.SITE_TITLE} — ${CONFIG.SITE_TAGLINE}`;
    document.title = fullTitle;

    // Canonical + OG URLs
    document.getElementById('canonical-url')?.setAttribute('href', `${CONFIG.BLOG_URL}/`);
    document.getElementById('og-url')?.setAttribute('content', `${CONFIG.BLOG_URL}/`);
    document.getElementById('og-type')?.setAttribute('content', 'website');

    // Titles & descriptions
    ['og-title', 'tw-title'].forEach(id =>
      Utils.qs(`#${id}`)?.setAttribute('content', fullTitle));
    ['og-desc', 'tw-desc'].forEach(id =>
      Utils.qs(`#${id}`)?.setAttribute('content', CONFIG.SITE_DESCRIPTION));
    document.getElementById('meta-desc')?.setAttribute('content', CONFIG.SITE_DESCRIPTION);

    // OG image
    document.getElementById('og-image')?.setAttribute('content', CONFIG.OG_IMAGE);
    document.getElementById('tw-image')?.setAttribute('content', CONFIG.OG_IMAGE);

    // Twitter handle
    document.querySelector('meta[name="twitter:site"]')?.setAttribute('content', CONFIG.TWITTER_HANDLE);

    // Favicon (dynamic update — avoids hardcoding in HTML per brand)
    const faviconEl = document.querySelector('link[rel="icon"]');
    if (faviconEl) faviconEl.href = CONFIG.FAVICON_URL;

    // Auspicious bar
    const ausLink = Utils.qs('.auspicious-text');
    if (ausLink) {
      ausLink.textContent = CONFIG.AUSPICIOUS_TEXT;
      ausLink.href        = CONFIG.AUSPICIOUS_URL;
      ausLink.setAttribute('aria-label', CONFIG.AUSPICIOUS_LABEL);
    }

    // Logo images (all .logo__img on page)
    document.querySelectorAll('.logo__img').forEach(img => {
      img.src = CONFIG.LOGO_IMG_URL;
      img.alt = CONFIG.LOGO_ALT;
    });

    // Logo link aria-label
    const logoLink = document.getElementById('logo-link');
    if (logoLink) logoLink.setAttribute('aria-label', `${CONFIG.BLOG_URL.replace('https://', '')} home`);

    // Footer
    const footerLinks = document.getElementById('footer-links');
    if (footerLinks) {
      footerLinks.innerHTML = CONFIG.SOCIAL_LINKS
        .map(s => `<a href="${s.url}" target="_blank" rel="noopener" aria-label="${s.label}"><i class="${s.icon}" aria-hidden="true"></i> <span>${s.label}</span></a>`)
        .join('');
    }

    // Current year
    document.querySelectorAll('[data-current-year]').forEach(el => el.textContent = new Date().getFullYear());

    // JSON-LD: Blog (homepage)
    const ldBlogs = document.getElementById('ld-blogs');
    if (ldBlogs) ldBlogs.textContent = JSON.stringify({
      "@context": "https://schema.org",
      "@type": "Blog",
      "name": CONFIG.SITE_TITLE,
      "url": `${CONFIG.BLOG_URL}/`,
      "description": CONFIG.SITE_DESCRIPTION,
      "publisher": {
        "@type": "Organization",
        "name": CONFIG.PUBLISHER_NAME,
        "url": CONFIG.PUBLISHER_URL,
        "logo": { "@type": "ImageObject", "url": CONFIG.PUBLISHER_LOGO }
      },
      "inLanguage": "en-US"
    });

    // JSON-LD: Organization
    const ldOrg = document.getElementById('ld-org');
    if (ldOrg) ldOrg.textContent = JSON.stringify({
      "@context": "https://schema.org",
      "@type": "Organization",
      "name": CONFIG.PUBLISHER_NAME,
      "url": CONFIG.PUBLISHER_URL,
      "logo": CONFIG.PUBLISHER_LOGO,
      "sameAs": CONFIG.SOCIAL_LINKS.map(s => s.url)
    });
  },

  renderHero(posts) {
    if (!posts.length) return;
    const p = posts[0];

    const words = p.title.split(' ');
    const last  = words.length > 1 ? words.pop() : '';
    const titleHtml = last
      ? `${Utils.escapeHtml(words.join(' '))} <em>${Utils.escapeHtml(last)}</em>`
      : `<em>${Utils.escapeHtml(p.title)}</em>`;

    const heroGrid = Utils.qs('.hero__grid');
    if (!heroGrid) return;

    heroGrid.innerHTML = `
      <div class="hero__featured" id="hero-featured-panel">
        <div class="hero__eyebrow">
          <span class="hero__eyebrow-dot"></span>
          ${CONFIG.HERO_EYEBROW}
        </div>
        <span class="hero__tag" id="hero-tag">${Utils.tagIcon(p.tag)} ${Utils.escapeHtml(p.tag)}</span>
        <h1 class="hero__title" id="hero-title">${titleHtml}</h1>
        <p class="hero__sub" id="hero-sub">${Utils.safeText(p.excerpt || CONFIG.HERO_SUB)}</p>
        <div class="meta" id="hero-meta">
          <span class="avatar">${Utils.escapeHtml(p.authorInitials)}</span>
          <span>${Utils.escapeHtml(p.author)}</span>
          <span class="meta-dot">·</span>
          <span>${Utils.fmtDateShort(p.date)}</span>
          <span class="meta-dot">·</span>
          <span><i class="fa-regular fa-clock"></i> ${p.readTime}</span>
          ${p.paywalled ? '<span class="members-badge"><i class="fa-solid fa-star"></i> Members</span>' : ''}
        </div>
        <button class="hero-link" id="hero-read-btn">Read post</button>
      </div>
      <aside class="hero__sidebar">
        <h3 class="sidebar__title">Also reading</h3>
        <ul class="sidebar__list" id="aside-list">
          <li class="loading-text">Loading…</li>
        </ul>
      </aside>`;

    Utils.qs('#hero-featured-panel').addEventListener('click', () => Router.go(p.slug));
    Utils.qs('#hero-read-btn').addEventListener('click', e => { e.stopPropagation(); Router.go(p.slug); });

    const aside = Utils.qs('#aside-list');
    // Skip posts already visible in the hero + top grid cards.
    // Sidebar shows items 7-11 so nothing duplicates the main grid.
    const sidebarStart = Math.min(7, Math.max(1, posts.length - 4));
    const items = posts.slice(sidebarStart, sidebarStart + 4);
    aside.innerHTML = items.length
      ? items.map(item => `
          <li>
            <button class="sidebar__link" data-slug="${Utils.escapeHtml(item.slug)}">
              ${Utils.tagIcon(item.tag)} ${Utils.escapeHtml(item.title)}
            </button>
            <span class="sidebar__date">
              <i class="fa-regular fa-calendar"></i> ${Utils.fmtDateShort(item.date)}
              <span class="meta-dot">·</span>
              <i class="fa-regular fa-clock"></i> ${Utils.escapeHtml(item.readTime)}
            </span>
          </li>`).join('')
      : '<li class="loading-text">No more posts</li>';

    aside.querySelectorAll('.sidebar__link[data-slug]').forEach(btn => {
      btn.addEventListener('click', e => { e.stopPropagation(); Router.go(btn.dataset.slug); });
    });
  },

  renderPosts(posts, showFeatured = false) {
    const grid = Utils.qs('#posts-grid');
    if (!posts.length) {
      grid.innerHTML = `<div class="empty-state"><i class="fa-solid fa-inbox empty-icon"></i><h3>No posts found</h3><p>Try a different topic or check back soon.</p></div>`;
      return;
    }
    grid.innerHTML = posts.map((p, i) => {
      const isFeat = showFeatured && i === 0;
      const visual = p.cover
        ? `<img src="${Utils.escapeHtml(p.cover)}" alt="${Utils.escapeHtml(p.title)}" class="card__cover-img" loading="lazy">`
        : `<i class="fa-solid fa-file-lines card__icon" aria-hidden="true"></i>`;
      return `<article class="card ${isFeat ? 'featured' : ''}" role="listitem" data-idx="${i}">
        <div class="card__visual">${visual}</div>
        <div class="card__content">
          <span class="card__tag" data-tag="${Utils.escapeHtml(p.tag)}"><i class="${TAG_ICONS[p.tag] || TAG_ICONS.Post}"></i> ${Utils.escapeHtml(p.tag)}</span>
          <h2 class="card__title">${Utils.escapeHtml(p.title)}</h2>
          <p class="card__excerpt">${Utils.safeText(p.excerpt)}</p>
          <div class="card__footer">
            <span class="card__author"><i class="fa-solid fa-user-pen"></i> ${Utils.escapeHtml(p.author)}</span>
            <span class="card__meta">
              <i class="fa-regular fa-calendar"></i> ${Utils.fmtDateShort(p.date)}
              <span class="meta-dot">·</span>
              <i class="fa-regular fa-clock"></i> ${Utils.escapeHtml(p.readTime)}
              ${p.paywalled ? '<span class="members-badge"><i class="fa-solid fa-star"></i></span>' : ''}
            </span>
          </div>
        </div>
      </article>`;
    }).join('');

    grid.querySelectorAll('.card').forEach(card => {
      const idx = parseInt(card.dataset.idx);
      card.setAttribute('tabindex', '0');
      card.setAttribute('aria-label', `Read: ${posts[idx].title}`);
      card.addEventListener('click', e => {
        const tagChip = e.target.closest('.card__tag');
        if (tagChip) {
          e.stopPropagation();
          Router.setQuery({ tag: posts[idx].tag, page: 1 });
          return;
        }
        Router.go(posts[idx].slug);
      });
      card.addEventListener('keydown', e => {
        if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); Router.go(posts[idx].slug); }
      });
    });
  },

  renderPagination(total, perPage, currentPage) {
    let container = Utils.qs('#pagination-container');
    if (!container) {
      container = document.createElement('div');
      container.id = 'pagination-container';
      const grid = Utils.qs('#posts-grid');
      if (grid && grid.parentNode) grid.parentNode.insertBefore(container, grid.nextSibling);
    }
    const totalPages = Math.ceil(total / perPage);
    if (totalPages <= 1) { container.innerHTML = ''; return; }

    const pageSet = new Set([1, totalPages]);
    for (let i = Math.max(1, currentPage - 1); i <= Math.min(totalPages, currentPage + 1); i++) pageSet.add(i);
    const sorted = [...pageSet].sort((a, b) => a - b);

    const items = [];
    let prev = 0;
    for (const p of sorted) {
      if (p - prev > 1) items.push('…');
      items.push(p);
      prev = p;
    }

    let html = `<nav class="pagination" aria-label="Post pages">`;
    html += `<button class="pag-btn${currentPage === 1 ? ' disabled' : ''}"
              data-page="${currentPage - 1}"
              aria-label="Previous page"
              ${currentPage === 1 ? 'disabled' : ''}>← Prev</button>`;

    for (const item of items) {
      if (item === '…') {
        html += `<span class="pag-ellipsis">…</span>`;
      } else if (item === currentPage) {
        html += `<button class="pag-btn active" disabled aria-current="page">${item}</button>`;
      } else {
        html += `<button class="pag-btn" data-page="${item}" aria-label="Go to page ${item}">${item}</button>`;
      }
    }

    html += `<button class="pag-btn${currentPage === totalPages ? ' disabled' : ''}"
              data-page="${currentPage + 1}"
              aria-label="Next page"
              ${currentPage === totalPages ? 'disabled' : ''}>Next →</button>`;
    html += `</nav>`;
    container.innerHTML = html;

    container.querySelectorAll('.pag-btn:not(.disabled):not([disabled])').forEach(btn => {
      btn.addEventListener('click', () => {
        const newPage = parseInt(btn.dataset.page);
        if (!newPage) return;
        Router.setQuery({ tag: AppState.filter === 'all' ? null : AppState.filter, page: newPage });
        Utils.qs('#posts-grid')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      });
    });
  },

  renderPost(post) {
    const app = Utils.qs('#post-article');
    const html = Utils.safeMarkdown(post.body || '');
    const paywalled = post.paywalled;
    const date = Utils.fmtDateShort(post.date);

    // ── Update all meta / SEO for this post ───────────────────
    const postUrl  = `${CONFIG.BLOG_URL}/post/${post.slug}`;
    const ogImg    = post.cover || CONFIG.OG_IMAGE;

    document.title = `${post.title} — ${CONFIG.SITE_TITLE}`;
    document.getElementById('canonical-url')?.setAttribute('href', postUrl);
    document.getElementById('meta-desc')?.setAttribute('content', post.excerpt);
    document.getElementById('og-type')?.setAttribute('content', 'article');
    ['og-title', 'tw-title'].forEach(id => Utils.qs(`#${id}`)?.setAttribute('content', post.title));
    ['og-desc',  'tw-desc' ].forEach(id => Utils.qs(`#${id}`)?.setAttribute('content', post.excerpt));
    document.getElementById('og-url')?.setAttribute('content', postUrl);
    document.getElementById('og-image')?.setAttribute('content', ogImg);
    document.getElementById('tw-image')?.setAttribute('content', ogImg);

    // JSON-LD: BlogPosting
    const ldBlogs = document.getElementById('ld-blogs');
    if (ldBlogs) ldBlogs.textContent = JSON.stringify({
      "@context": "https://schema.org", "@type": "BlogPosting",
      "headline": post.title, "description": post.excerpt, "datePublished": post.date,
      ...(post.cover ? { "image": post.cover } : {}),
      "author": { "@type": "Person", "name": post.author },
      "publisher": {
        "@type": "Organization",
        "name": CONFIG.PUBLISHER_NAME,
        "url": CONFIG.PUBLISHER_URL,
        "logo": { "@type": "ImageObject", "url": CONFIG.PUBLISHER_LOGO }
      },
      "mainEntityOfPage": { "@type": "WebPage", "@id": postUrl },
      "url": postUrl, "keywords": post.tag, "inLanguage": "en-US"
    });

    // JSON-LD: BreadcrumbList
    const ldOrg = document.getElementById('ld-org');
    if (ldOrg) ldOrg.textContent = JSON.stringify({
      "@context": "https://schema.org", "@type": "BreadcrumbList",
      "itemListElement": [
        { "@type": "ListItem", "position": 1, "name": "Home",     "item": `${CONFIG.BLOG_URL}/` },
        { "@type": "ListItem", "position": 2, "name": post.tag,   "item": `${CONFIG.BLOG_URL}/?tag=${post.tag}` },
        { "@type": "ListItem", "position": 3, "name": post.title, "item": postUrl }
      ]
    });

    // ── Paywall ───────────────────────────────────────────────
    let content = '';
    if (paywalled && !AppState.isMember) {
      const div = document.createElement('div');
      div.innerHTML = html;
      const blocks = [...div.children];
      // Always show TOC/h1 blocks; count only content blocks toward the preview limit
      const alwaysShow = el => el.matches('nav.toc, h1');
      const contentBlocks = blocks.filter(el => !alwaysShow(el));
      const freeContent   = contentBlocks.slice(0, 12);
      const tocBlocks     = blocks.filter(el => alwaysShow(el));
      const free  = [...tocBlocks, ...freeContent].map(n => n.outerHTML).join('');
      content = `<div class="paywall-wrap" data-blog-url="${CONFIG.BLOG_URL}"><div class="post-body paywall-fade">${free || '<p>' + (post.excerpt || '') + '</p>'}</div></div>
         <div class="paywall-gate"><div class="paywall-card">
           <i class="fa-solid fa-lock paywall-icon"></i>
           <h3>Members only</h3>
           <p>This post is for members. Purchase a membership to unlock all gated posts — you'll receive a license key instantly.</p>
           <div class="paywall-actions">
             <a class="btn primary" href="${CONFIG.MEMBERSHIP_URL}" target="_blank" rel="noopener">
               <i class="fa-solid fa-cart-shopping"></i> Get Access — ${CONFIG.MEMBERSHIP_PRICE}
             </a>
             <button class="btn" id="back-btn"><i class="fa-solid fa-arrow-left"></i> Back to posts</button>
           </div>
           <div class="paywall-key-wrap">
             <p class="paywall-key-label">Already a member? Enter your license key:</p>
             <div class="paywall-key-row">
               <input type="text" id="license-input" class="paywall-key-input" placeholder="XXXXXXXX-XXXXXXXX-XXXXXXXX-XXXXXXXX" spellcheck="false" autocomplete="off">
               <button class="btn primary" id="unlock-btn"><i class="fa-solid fa-unlock"></i> Unlock</button>
             </div>
             <p class="paywall-key-status" id="key-status" aria-live="polite"></p>
           </div>
         </div></div>`;
    } else {
      content = `<div class="post-body">${html}</div>`;
    }

    const liked = localStorage.getItem(`liked:${post.slug}`) === '1';

    app.innerHTML = `
      <header class="post-header">
        <button class="post-back" id="post-back-btn"><i class="fa-solid fa-arrow-left"></i> Back</button>
        <span class="post-tag">${Utils.tagIcon(post.tag)} ${Utils.escapeHtml(post.tag)}</span>
        <h1 class="post-title">${Utils.escapeHtml(post.title)}</h1>
        ${(() => {
          if (!post.excerpt) return '';
          // Suppress header excerpt if the post body opens with the same text
          const bodyStart = (post.body || '').replace(/^#{1,6}\s+[^\n]+\n+/, '')
            .replace(/[*_`#>\[\]]/g, '').trim().substring(0, 80).toLowerCase();
          const excStart  = post.excerpt.replace(/[*_`#>\[\]]/g, '').trim().substring(0, 80).toLowerCase();
          if (bodyStart && excStart && bodyStart.startsWith(excStart.substring(0, 60))) return '';
          return `<p class="post-excerpt">${Utils.safeText(post.excerpt)}</p>`;
        })()}
        <div class="post-meta">
          <span class="avatar">${Utils.escapeHtml(post.authorInitials)}</span>
          <div class="meta-info">
            <div class="meta-name">${Utils.escapeHtml(post.author)}</div>
            <div class="meta-details">
              <span><i class="fa-regular fa-calendar"></i> ${date}</span>
              <span class="meta-dot">·</span>
              <span><i class="fa-regular fa-clock"></i> ${Utils.escapeHtml(post.readTime)}</span>
              ${paywalled ? '<span class="meta-dot">·</span><span class="members-badge"><i class="fa-solid fa-star"></i> Members</span>' : ''}
            </div>
          </div>
          <div class="meta-actions">
            ${!(paywalled && !AppState.isMember) ? '<button class="btn" id="print-btn"><i class="fa-solid fa-print"></i> Print</button>' : ''}
            <button class="btn" id="share-btn"><i class="fa-solid fa-share-nodes"></i> Share</button>
          </div>
        </div>
      </header>
      ${post.cover
        ? `<div class="post-cover post-cover--img"><img src="${Utils.escapeHtml(post.cover)}" alt="${Utils.escapeHtml(post.title)}" class="post-cover__img"></div>`
        : ''
      }
      ${content}
      ${(() => {
        const links = [
          post.authorLinkedin ? `<a href="${Utils.escapeHtml(post.authorLinkedin)}" target="_blank" rel="noopener" class="author-card__link" aria-label="LinkedIn"><i class="fa-brands fa-linkedin"></i> LinkedIn</a>` : '',
          post.authorGithub   ? `<a href="${Utils.escapeHtml(post.authorGithub)}"   target="_blank" rel="noopener" class="author-card__link" aria-label="GitHub"><i class="fa-brands fa-github"></i> GitHub</a>` : '',
          post.authorWebsite  ? `<a href="${Utils.escapeHtml(post.authorWebsite)}"  target="_blank" rel="noopener" class="author-card__link" aria-label="Website"><i class="fa-solid fa-globe"></i> Website</a>` : '',
        ].filter(Boolean).join('');
        return `<div class="author-card">
          <span class="author-card__avatar">${Utils.escapeHtml(post.authorInitials)}</span>
          <div class="author-card__body">
            <div class="author-card__label">Written by</div>
            <div class="author-card__name">${Utils.escapeHtml(post.author)}</div>
            ${post.authorRole ? `<div class="author-card__role">${Utils.safeText(post.authorRole)}</div>` : ''}
            ${post.authorBio  ? `<p class="author-card__bio">${Utils.safeText(post.authorBio)}</p>` : ''}
            ${links ? `<div class="author-card__links">${links}</div>` : ''}
          </div>
        </div>`;
      })()}
      <footer class="post-footer">
        <div class="post-tags">
          <button class="tag-chip" data-back-tag="${Utils.escapeHtml(post.tag)}" title="Browse all ${Utils.escapeHtml(post.tag)} posts">${Utils.tagIcon(post.tag)} More ${Utils.escapeHtml(post.tag)}</button>
          <button class="tag-chip" id="all-posts-btn"><i class="fa-solid fa-grip"></i> All Posts</button>
        </div>
        <div class="meta-actions">
          <button class="btn like ${liked ? 'reacted' : ''}" id="like-btn">
            <i class="fa-${liked ? 'solid' : 'regular'} fa-heart"></i> ${liked ? 'Liked' : 'Like'}
          </button>
          <button class="btn" id="footer-copy-link-btn" aria-label="Copy link"><i class="fa-solid fa-link"></i> Copy link</button>
          <button class="btn" id="footer-share-btn"><i class="fa-solid fa-share-nodes"></i> Share</button>
          ${!(paywalled && !AppState.isMember) ? '<button class="btn" id="footer-print-btn"><i class="fa-solid fa-print"></i> Print</button>' : ''}
        </div>
        <div class="post-nav" id="post-nav-btns"></div>
      </footer>`;

    // ── Adaptive paywall fade ─────────────────────────────────
    // After the DOM is painted, measure the preview's natural height.
    // • Short preview  (<= threshold): show all content fully — no clip, no fade.
    //   This prevents a jarring hard cut on posts that only have a paragraph or two of free content.
    // • Tall preview   (>  threshold): cap to FADE_CAP px and apply the gradient mask
    //   so the fade always lands visibly within the rendered text, never below it.
    const fadeEl = app.querySelector('.paywall-fade');
    if (fadeEl) {
      const FADE_THRESHOLD = 380; // px — shorter than this → show in full
      const FADE_CAP       = 460; // px — cap height when clipping
      requestAnimationFrame(() => {
        // scrollHeight gives the full rendered height even when overflow:hidden
        const naturalH = fadeEl.scrollHeight;
        if (naturalH > FADE_THRESHOLD) {
          fadeEl.style.maxHeight = FADE_CAP + 'px';
          fadeEl.classList.add('paywall-fade--clipped');
        } else {
          // Content is short — reveal it fully so the gate appears directly below
          fadeEl.style.maxHeight = naturalH + 'px';
          // No mask needed; gate follows immediately
        }
      });
    }

    // ── Wire up all post interactions ─────────────────────────
    app.querySelector('#post-back-btn')?.addEventListener('click', () => Router.back());
    app.querySelector('#print-btn')?.addEventListener('click', () => window.print());
    app.querySelector('#all-posts-btn')?.addEventListener('click', () => Router.back());
    app.querySelector('[data-back-tag]')?.addEventListener('click', function() {
      Router.back(this.dataset.backTag);
    });
    app.querySelector('#like-btn')?.addEventListener('click', function () {
      const is = this.classList.toggle('reacted');
      this.innerHTML = `<i class="fa-${is ? 'solid' : 'regular'} fa-heart"></i> ${is ? 'Liked' : 'Like'}`;
      localStorage.setItem(`liked:${post.slug}`, is ? '1' : '0');
    });

    // Prev / Next navigation
    const navEl = app.querySelector('#post-nav-btns');
    if (navEl && AppState.posts.length) {
      const idx  = AppState.posts.findIndex(p => p.slug === post.slug);
      const prev = idx < AppState.posts.length - 1 ? AppState.posts[idx + 1] : null;
      const next = idx > 0 ? AppState.posts[idx - 1] : null;
      navEl.innerHTML = `
        ${prev ? `<button class="post-nav-btn" id="nav-prev">
           <div class="nav-label"><i class="fa-solid fa-arrow-left"></i> Older</div>
           <div class="nav-title">${Utils.escapeHtml(prev.title)}</div>
         </button>` : '<div class="post-nav-btn post-nav-btn--empty"></div>'}
        ${next ? `<button class="post-nav-btn post-nav-btn--right" id="nav-next">
           <div class="nav-label">Newer <i class="fa-solid fa-arrow-right"></i></div>
           <div class="nav-title">${Utils.escapeHtml(next.title)}</div>
         </button>` : '<div class="post-nav-btn post-nav-btn--right post-nav-btn--empty"></div>'}`;
      navEl.querySelector('#nav-prev')?.addEventListener('click', () => Router.go(prev.slug));
      navEl.querySelector('#nav-next')?.addEventListener('click', () => Router.go(next.slug));
    }

    app.querySelector('#share-btn')?.addEventListener('click', () => UI.share(post));
    app.querySelector('#footer-share-btn')?.addEventListener('click', () => UI.share(post));
    app.querySelector('#footer-copy-link-btn')?.addEventListener('click', () => {
      UI.copyToClipboard(location.href).then(() =>
        UI.showToast('<i class="fa-solid fa-check"></i> Link copied')
      );
    });
    app.querySelector('#footer-print-btn')?.addEventListener('click', () => window.print());

    app.querySelector('#back-btn')?.addEventListener('click', () => Router.back());

    // ── Lemon Squeezy license key verification ───────────────────
    const unlockBtn   = app.querySelector('#unlock-btn');
    const licenseInput = app.querySelector('#license-input');
    const keyStatus   = app.querySelector('#key-status');

    if (unlockBtn && licenseInput) {
      const setStatus = (msg, isError) => {
        if (!keyStatus) return;
        keyStatus.textContent = msg;
        keyStatus.className = 'paywall-key-status ' + (isError ? 'paywall-key-status--error' : 'paywall-key-status--ok');
      };

      const doVerify = async () => {
        const key = licenseInput.value.trim();
        if (!key) { setStatus('Please enter your license key.', true); return; }

        unlockBtn.disabled = true;
        unlockBtn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Checking…';
        setStatus('', false);

        try {
          // Lemon Squeezy license validate — CORS-enabled, no server needed
          const res = await fetch('https://api.lemonsqueezy.com/v1/licenses/validate', {
            method: 'POST',
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
            body: new URLSearchParams({ license_key: key })
          });
          const data = await res.json();

          if (data.valid) {
            localStorage.setItem('blogs_member', '1');
            localStorage.setItem('blogs_license', btoa(key));
            AppState.isMember = true;
            // Clear the stripped cache so the full body is re-fetched
            delete AppState.postsCache[post.slug];
            setStatus('', false);
            Router.render();
          } else {
            setStatus(data.error || 'Invalid license key. Please try again.', true);
            unlockBtn.disabled = false;
            unlockBtn.innerHTML = '<i class="fa-solid fa-unlock"></i> Unlock';
          }
        } catch (err) {
          setStatus('Could not reach the license server. Check your connection.', true);
          unlockBtn.disabled = false;
          unlockBtn.innerHTML = '<i class="fa-solid fa-unlock"></i> Unlock';
        }
      };

      unlockBtn.addEventListener('click', doVerify);
      licenseInput.addEventListener('keydown', e => { if (e.key === 'Enter') doVerify(); });
    }

    // Code blocks: copy button + language label
    app.querySelectorAll('pre').forEach(pre => {
      const wrap = document.createElement('div');
      wrap.className = 'code-block';
      const bar = document.createElement('div');
      bar.className = 'code-block__bar';
      const lang = pre.querySelector('code')?.className.match(/language-(\w+)/)?.[1];
      const langLabel = Object.assign(document.createElement('span'), { className: 'code-lang', textContent: lang || '' });
      bar.appendChild(langLabel);
      const btn = document.createElement('button');
      btn.className = 'copy-btn';
      btn.innerHTML = `<i class="fa-regular fa-copy"></i> Copy`;
      btn.addEventListener('click', async () => {
        try { await navigator.clipboard.writeText(pre.textContent); } catch {
          try {
            const ta = Object.assign(document.createElement('textarea'), { value: pre.textContent });
            ta.style.cssText = 'position:fixed;opacity:0';
            document.body.appendChild(ta); ta.select(); document.execCommand('copy'); ta.remove();
          } catch { /* clipboard unavailable */ }
        }
        btn.innerHTML = `<i class="fa-solid fa-check"></i> Copied`;
        btn.classList.add('copied');
        setTimeout(() => { btn.innerHTML = `<i class="fa-regular fa-copy"></i> Copy`; btn.classList.remove('copied'); }, 2000);
      });
      bar.appendChild(btn);
      wrap.appendChild(bar);
      pre.parentNode.insertBefore(wrap, pre);
      wrap.appendChild(pre);
    });

    // Tables: Copy CSV button
    app.querySelectorAll('.post-body table, .paywall-fade table').forEach(table => {
      const wrap = document.createElement('div');
      wrap.className = 'table-wrap';
      table.parentNode.insertBefore(wrap, table);
      wrap.appendChild(table);
      const bar = document.createElement('div');
      bar.className = 'table-bar';
      const copyBtn = document.createElement('button');
      copyBtn.className = 'table-copy-btn btn';
      copyBtn.innerHTML = `<i class="fa-regular fa-copy"></i> Copy CSV`;
      copyBtn.addEventListener('click', async () => {
        const rows = [...table.querySelectorAll('tr')];
        const csv  = rows.map(r => [...r.querySelectorAll('th,td')]
          .map(c => `"${c.textContent.replace(/"/g, '""')}"`)
          .join(',')).join('\n');
        try { await navigator.clipboard.writeText(csv); } catch {
          try {
            const ta = Object.assign(document.createElement('textarea'), { value: csv });
            ta.style.cssText = 'position:fixed;opacity:0';
            document.body.appendChild(ta); ta.select(); document.execCommand('copy'); ta.remove();
          } catch { /* clipboard unavailable */ }
        }
        copyBtn.innerHTML = `<i class="fa-solid fa-check"></i> Copied`;
        copyBtn.classList.add('copied');
        setTimeout(() => { copyBtn.innerHTML = `<i class="fa-regular fa-copy"></i> Copy CSV`; copyBtn.classList.remove('copied'); }, 2000);
      });
      bar.appendChild(copyBtn);
      wrap.insertBefore(bar, table);
    });

    if (typeof Prism !== 'undefined') Prism.highlightAll();
    window.scrollTo({ top: 0, behavior: 'instant' });

    // ── Ads — inject mid-post on free posts only ─────────────────
    if (!paywalled) {
      const postBody = app.querySelector('.post-body');
      if (postBody) {
        const paras = postBody.querySelectorAll('p');
        const insertAfter = paras[Math.floor(paras.length / 3)] || paras[0];
        if (insertAfter) {
          const adWrap = document.createElement('div');
          adWrap.className = 'ad-wrap';

          if (CONFIG.ADSENSE_CLIENT && CONFIG.ADSENSE_SLOT) {
            // ── Google AdSense unit ──────────────────────────────
            adWrap.innerHTML = `
              <ins class="adsbygoogle ad-unit"
                   style="display:block"
                   data-ad-client="${CONFIG.ADSENSE_CLIENT}"
                   data-ad-slot="${CONFIG.ADSENSE_SLOT}"
                   data-ad-format="auto"
                   data-full-width-responsive="true"></ins>`;
            insertAfter.after(adWrap);
            const pushAd = () => {
              try { (window.adsbygoogle = window.adsbygoogle || []).push({}); } catch(e) {}
            };
            if (!document.getElementById('adsense-script')) {
              const s = document.createElement('script');
              s.id = 'adsense-script';
              s.async = true;
              s.src = `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${CONFIG.ADSENSE_CLIENT}`;
              s.crossOrigin = 'anonymous';
              s.onload = pushAd;
              document.head.appendChild(s);
            } else {
              // Script already loaded — push immediately
              pushAd();
            }

          } else if (CONFIG.HOUSE_AD_ENABLED && !AppState.isMember) {
            // ── House ad — skip if dismissed this session ────────
            if (sessionStorage.getItem('house_ad_dismissed') !== '1') {
            adWrap.innerHTML = `
              <div class="house-ad">
                <button class="house-ad__close" aria-label="Dismiss" title="Dismiss">×</button>
                <div class="house-ad__eyebrow">
                  <i class="fa-solid fa-star"></i>
                  <span>Members Only</span>
                </div>
                <h3 class="house-ad__headline">${CONFIG.HOUSE_AD_TEXT}</h3>
                <div class="house-ad__footer">
                  <a href="${CONFIG.MEMBERSHIP_URL}" target="_blank" rel="noopener" class="house-ad__cta">
                    <i class="fa-solid fa-unlock"></i> ${CONFIG.HOUSE_AD_CTA}
                  </a>
                  <span class="house-ad__price">${CONFIG.MEMBERSHIP_PRICE}</span>
                </div>
              </div>`;
            insertAfter.after(adWrap);
            adWrap.querySelector('.house-ad__close')?.addEventListener('click', () => {
              adWrap.style.display = 'none';
              sessionStorage.setItem('house_ad_dismissed', '1');
            });
            }
          }
        }
      }
    }
    // Smooth scroll for in-page anchor links
    app.querySelectorAll('a[href^="#"]').forEach(a => {
      a.addEventListener('click', e => {
        e.preventDefault();
        const id = decodeURIComponent(a.getAttribute('href').slice(1));
        document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      });
    });
  }
};

// =========================================
// 5. ROUTER
// =========================================
const Router = {
  go(slug) {
    history.pushState({ slug }, '', `/post/${encodeURIComponent(slug)}`);
    this.render();
  },
  back(tag) {
    this.setQuery({ tag: tag || null, page: 1 });
  },
  getSlug() {
    // Handle /posts/slug (raw GitHub Pages path) → silently rewrite to /post/slug
    const rawMd = location.pathname.match(/^\/posts\/(.+?)(?:\.md)?$/);
    if (rawMd) {
      const slug = decodeURIComponent(rawMd[1]);
      history.replaceState({}, '', `/post/${encodeURIComponent(slug)}`);
      return slug;
    }
    const m = location.pathname.match(/^\/post\/(.+)$/);
    return m ? decodeURIComponent(m[1]) : null;
  },
  getParams() {
    const qs = new URLSearchParams(location.search);
    return {
      tag:  qs.get('tag') || null,
      page: Math.max(1, parseInt(qs.get('page')) || 1)
    };
  },
  setQuery({ tag, page } = {}) {
    const qs = new URLSearchParams();
    if (tag && tag !== 'all') qs.set('tag', tag);
    if (page > 1) qs.set('page', page);
    history.pushState({}, '', qs.toString() ? `/?${qs.toString()}` : '/');
    this.render();
  },
  async render() {
    const slug    = this.getSlug();
    const indexEl = document.getElementById('view-index');
    const postEl  = document.getElementById('view-post');
    const readBar = document.getElementById('reading-bar');

    // Close search bar on every navigation
    const searchBar   = Utils.qs('#search-bar');
    const searchInput = Utils.qs('#search-input');
    if (searchBar?.classList.contains('open')) {
      searchBar.classList.remove('open');
      searchBar.setAttribute('aria-hidden', 'true');
      if (searchInput) { searchInput.value = ''; AppState.search = ''; }
    }

    if (slug) {
      // ── Post view ─────────────────────────────────────────
      indexEl.style.display = 'none';
      postEl.style.display  = '';
      if (readBar) readBar.style.display = '';

      document.querySelectorAll('.nav a, .mobile-nav a').forEach(a =>
        a.classList.toggle('active', a.getAttribute('href') === '/')
      );

      Utils.qs('#post-article').innerHTML =
        `<div class="loading-spinner"><div class="spinner"></div></div>`;

      try {
        const post = AppState.postsCache[slug] || await DataLoader.fetchBody(slug);
        if (post && (post.body || post.paywalled)) {
          Renderer.renderPost(post);
        } else {
          throw new Error('body missing');
        }
      } catch {
        Utils.qs('#post-article').innerHTML = `
          <div class="empty-state">
            <i class="fa-solid fa-file-circle-xmark empty-icon"></i>
            <h3>Post not found</h3>
            <p>The post you're looking for doesn't exist or failed to load.</p>
            <button class="btn primary" id="err-back-btn">
              <i class="fa-solid fa-arrow-left"></i> Back to posts
            </button>
          </div>`;
        Utils.qs('#err-back-btn')?.addEventListener('click', () => Router.back());
      }
    } else {
      // ── Index view ────────────────────────────────────────
      indexEl.style.display = '';
      postEl.style.display  = 'none';
      if (readBar) { readBar.style.display = 'none'; readBar.style.width = '0%'; }

      // Sync search state from the actual input value so any navigation path
      // that didn't go through a close-handler can't leave a stale filter active.
      const _searchInput = Utils.qs('#search-input');
      if (_searchInput) AppState.search = _searchInput.value.toLowerCase().trim();

      // Reset title + meta to homepage defaults
      document.title = `${CONFIG.SITE_TITLE} — ${CONFIG.SITE_TAGLINE}`;
      document.getElementById('canonical-url')?.setAttribute('href', `${CONFIG.BLOG_URL}/`);
      document.getElementById('og-type')?.setAttribute('content', 'website');
      document.getElementById('og-url')?.setAttribute('content', `${CONFIG.BLOG_URL}/`);
      ['og-title', 'tw-title'].forEach(id =>
        Utils.qs(`#${id}`)?.setAttribute('content', `${CONFIG.SITE_TITLE} — ${CONFIG.SITE_TAGLINE}`));
      ['og-desc', 'tw-desc'].forEach(id =>
        Utils.qs(`#${id}`)?.setAttribute('content', CONFIG.SITE_DESCRIPTION));

      const { tag, page } = this.getParams();
      AppState.filter = tag || 'all';
      AppState.pagination.page = page;

      document.querySelectorAll('.nav a, .mobile-nav a').forEach(a => {
        const href = a.getAttribute('href');
        const hrefTag = href?.includes('?tag=') ? href.split('?tag=')[1].toLowerCase() : null;
        const activeTag = tag ? tag.toLowerCase() : null;
        a.classList.toggle('active', hrefTag === activeTag || (!hrefTag && !tag && href === '/'));
      });

      document.querySelectorAll('.chip').forEach(chip =>
        chip.classList.toggle('active', chip.dataset.tag.toLowerCase() === AppState.filter.toLowerCase())
      );

      let filtered = AppState.filter === 'all'
        ? AppState.posts
        : AppState.posts.filter(p => p.tag.toLowerCase() === AppState.filter.toLowerCase());

      if (AppState.search) {
        const q = AppState.search.toLowerCase();
        filtered = filtered.filter(p => {
          if (p.title.toLowerCase().includes(q)) return true;
          if (p.excerpt.toLowerCase().includes(q)) return true;
          if (p.tag.toLowerCase().includes(q)) return true;
          // Never search gated body content for non-members
          if (p.paywalled && !AppState.isMember) return false;
          return (AppState.postsCache[p.slug]?.body || '').toLowerCase().includes(q);
        });
      }

      const { perPage } = AppState.pagination;
      const totalPages = Math.max(1, Math.ceil(filtered.length / perPage));
      if (AppState.pagination.page > totalPages) AppState.pagination.page = totalPages;
      const start   = (AppState.pagination.page - 1) * perPage;
      const visible = filtered.slice(start, start + perPage);

      const showFeatured = AppState.filter === 'all' && AppState.pagination.page === 1 && !AppState.search;

      // Hero already features posts[0], so strip it from the grid
      const gridPosts = (showFeatured && visible.length > 1)
        ? visible.slice(1)
        : visible;

      const st = Utils.qs('#section-title');
      if (st) st.textContent = AppState.search
        ? `Results for "${AppState.search}"`
        : (AppState.filter === 'all' ? 'Latest Posts' : AppState.filter);

      const heroEl = Utils.qs('.hero');
      const heroVisible = !AppState.search && AppState.filter === 'all';
      if (heroEl) {
        if (heroVisible) {
          heroEl.style.animation = '';
          heroEl.style.display   = '';
        } else {
          heroEl.style.display = 'none';
        }
      }

      Renderer.renderPosts(gridPosts, showFeatured);
      Renderer.renderPagination(filtered.length, perPage, AppState.pagination.page);

      if (AppState.search) {
        Utils.qs('.posts')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    }
  }
};

// =========================================
// 6. UI & EVENTS
// =========================================
const UI = {
  showError(title, detail, code) {
    const grid = Utils.qs('#posts-grid');
    if (!grid) return;
    grid.innerHTML = `<div class="empty-state"><i class="fa-solid fa-triangle-exclamation empty-icon" style="color:var(--color-error)"></i><h3>${Utils.escapeHtml(title)}</h3><p>${Utils.escapeHtml(detail)}</p>${code ? `<pre><code>${Utils.escapeHtml(code)}</code></pre>` : ''}</div>`;
  },

  initTheme() {
    const btn  = Utils.qs('#theme-btn');
    const icon = Utils.qs('#theme-icon');
    const PRISM_DARK  = 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-tomorrow.min.css';
    const PRISM_LIGHT = 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism.min.css';
    const apply = t => {
      document.documentElement.setAttribute('data-theme', t);
      AppState.theme = t;
      localStorage.setItem('blogs-theme', t);
      if (icon) icon.className = t === 'dark' ? 'fa-solid fa-sun' : 'fa-solid fa-moon';
      const prismLink = document.getElementById('prism-theme');
      if (prismLink) prismLink.href = t === 'dark' ? PRISM_DARK : PRISM_LIGHT;
    };
    apply(AppState.theme);
    btn?.addEventListener('click', () =>
      apply(document.documentElement.getAttribute('data-theme') === 'dark' ? 'light' : 'dark')
    );
    matchMedia('(prefers-color-scheme: dark)').addEventListener('change', e => {
      if (!localStorage.getItem('blogs-theme')) apply(e.matches ? 'dark' : 'light');
    });
  },

  initMenu() {
    const btn = Utils.qs('#menu-toggle');
    const nav = Utils.qs('#mobile-nav');
    btn?.addEventListener('click', () => {
      const open = nav?.classList.toggle('open');
      btn.classList.toggle('open', open);
      btn.setAttribute('aria-expanded', open ? 'true' : 'false');
      nav?.setAttribute('aria-hidden', open ? 'false' : 'true');
    });
    nav?.addEventListener('click', e => {
      if (e.target.tagName === 'A' || e.target.closest('a')) {
        nav.classList.remove('open');
        btn.classList.remove('open');
        btn.setAttribute('aria-expanded', 'false');
        nav.setAttribute('aria-hidden', 'true');
      }
    });
  },

  initSearch() {
    const toggleBtn = Utils.qs('#search-toggle');
    const closeBtn  = Utils.qs('#search-close');
    const searchBar = Utils.qs('#search-bar');
    const input     = Utils.qs('#search-input');
    toggleBtn?.addEventListener('click', () => {
      const open = searchBar.classList.toggle('open');
      searchBar.setAttribute('aria-hidden', open ? 'false' : 'true');
      if (open) setTimeout(() => input?.focus(), 80);
    });
    closeBtn?.addEventListener('click', () => {
      searchBar.classList.remove('open');
      searchBar.setAttribute('aria-hidden', 'true');
      if (input) { input.value = ''; input.dispatchEvent(new Event('input')); }
    });
    input?.addEventListener('input', e => {
      AppState.search = e.target.value.toLowerCase().trim();
      if (Router.getSlug()) return;
      AppState.pagination.page = 1;
      Router.render();
      const live = Utils.qs('#search-live');
      if (live && AppState.search) {
        const q = AppState.search;
        const count = AppState.posts.filter(p => {
          if (p.title.toLowerCase().includes(q)) return true;
          if (p.excerpt.toLowerCase().includes(q)) return true;
          if (p.tag.toLowerCase().includes(q)) return true;
          if (p.paywalled && !AppState.isMember) return false;
          return (AppState.postsCache[p.slug]?.body || '').toLowerCase().includes(q);
        }).length;
        live.textContent = `${count} result${count !== 1 ? 's' : ''} for "${AppState.search}"`;
      } else if (live) {
        live.textContent = '';
      }
    });
    document.addEventListener('keydown', e => {
      if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
        e.preventDefault();
        searchBar.classList.add('open');
        searchBar.setAttribute('aria-hidden', 'false');
        setTimeout(() => input?.focus(), 80);
      }
      if (e.key === 'Escape' && searchBar.classList.contains('open')) {
        searchBar.classList.remove('open');
        searchBar.setAttribute('aria-hidden', 'true');
        if (input) { input.value = ''; input.dispatchEvent(new Event('input')); }
      }
    });
  },

  initFilters() {
    const bar = Utils.qs('#tag-bar');
    if (!bar) return;
    const tags = ['all', ...new Set(AppState.posts.map(p => p.tag))];
    bar.innerHTML = tags.map(t =>
      `<button class="chip ${t === AppState.filter ? 'active' : ''}" data-tag="${t}">${t !== 'all' ? Utils.tagIcon(t) + ' ' : ''}${t === 'all' ? 'All' : t}</button>`
    ).join('');
    bar.addEventListener('click', e => {
      const btn = e.target.closest('.chip');
      if (!btn) return;
      bar.querySelectorAll('.chip').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      AppState.search = '';
      const input = Utils.qs('#search-input');
      if (input) input.value = '';
      Router.setQuery({ tag: btn.dataset.tag === 'all' ? null : btn.dataset.tag, page: 1 });
    });
  },

  initBackTop() {
    const btn = Utils.qs('#back-top');
    if (!btn) return;
    window.addEventListener('scroll', () => btn.classList.toggle('show', window.scrollY > 400), { passive: true });
    btn.addEventListener('click', () => scrollTo({ top: 0, behavior: 'smooth' }));
  },

  initReadingBar() {
    const bar = Utils.qs('#reading-bar');
    if (!bar) return;
    window.addEventListener('scroll', () => {
      const total = document.documentElement.scrollHeight - window.innerHeight;
      bar.style.width = total > 0 ? (window.scrollY / total * 100) + '%' : '0%';
    }, { passive: true });
  },

  initLogoLink() {
    document.addEventListener('click', e => {
      const a = e.target.closest('a[href]');
      if (!a) return;
      const href = a.getAttribute('href');
      if (!href || href.startsWith('http') || href.startsWith('//') || href.startsWith('#') || href.startsWith('mailto:') || href.startsWith('tel:')) return;
      e.preventDefault();
      if (location.pathname + location.search !== href) {
        history.pushState({}, '', href);
        Router.render();
      }
    });
  },

  showToast(msg) {
    const toast = Object.assign(document.createElement('div'), {
      className: 'toast',
      innerHTML: msg
    });
    document.body.appendChild(toast);
    setTimeout(() => toast.classList.add('show'), 10);
    setTimeout(() => { toast.classList.remove('show'); setTimeout(() => toast.remove(), 300); }, 2500);
  },

  copyToClipboard(text) {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      return navigator.clipboard.writeText(text).catch(() => {
        const ta = Object.assign(document.createElement('textarea'), { value: text });
        ta.style.cssText = 'position:fixed;opacity:0;top:0;left:0';
        document.body.appendChild(ta); ta.focus(); ta.select();
        try { document.execCommand('copy'); } catch {}
        ta.remove();
      });
    }
    const ta = Object.assign(document.createElement('textarea'), { value: text });
    ta.style.cssText = 'position:fixed;opacity:0;top:0;left:0';
    document.body.appendChild(ta); ta.focus(); ta.select();
    try { document.execCommand('copy'); } catch {}
    ta.remove();
    return Promise.resolve();
  },

  share(post) {
    const url   = location.href;
    const title = post ? `${post.title} — ${CONFIG.SITE_TITLE}` : document.title;
    const text  = post?.excerpt || '';
    if (navigator.share) {
      navigator.share({ title, text, url }).catch(err => {
        if (err && err.name !== 'AbortError') {
          UI.copyToClipboard(url).then(() =>
            UI.showToast('<i class="fa-solid fa-check"></i> Link copied')
          );
        }
      });
    } else {
      UI.copyToClipboard(url).then(() =>
        UI.showToast('<i class="fa-solid fa-check"></i> Link copied')
      );
    }
  }
};

// =========================================
// 7. BOOTSTRAP
// =========================================
document.addEventListener('DOMContentLoaded', async () => {
  Renderer.applyBranding();
  UI.initTheme();
  UI.initMenu();
  UI.initBackTop();
  UI.initReadingBar();
  UI.initSearch();
  UI.initLogoLink();

  const loadGrid = Utils.qs('#posts-grid');
  if (loadGrid) loadGrid.innerHTML = '<div class="loading-spinner"><div class="spinner"></div></div>';

  const posts  = await DataLoader.load();
  const loader = Utils.qs('#page-loader');

  if (posts) {
    AppState.posts = posts;
    Renderer.renderHero(posts);
    UI.initFilters();
    Router.render();
  }

  // Dismiss full-page loader
  if (loader) {
    const bar = loader.querySelector('.loader__bar');
    if (bar) { bar.style.animation = 'none'; bar.style.width = '100%'; }
    requestAnimationFrame(() => {
      setTimeout(() => loader.classList.add('hidden'), 80);
    });
  }

  window.addEventListener('popstate', () => {
    const mobileNav = Utils.qs('#mobile-nav');
    const menuBtn   = Utils.qs('#menu-toggle');
    if (mobileNav?.classList.contains('open')) {
      mobileNav.classList.remove('open');
      menuBtn?.classList.remove('open');
      menuBtn?.setAttribute('aria-expanded', 'false');
      mobileNav.setAttribute('aria-hidden', 'true');
    }
    // Clear stale search state so back-navigation shows the correct listing
    const searchInput = Utils.qs('#search-input');
    if (searchInput) { searchInput.value = ''; }
    AppState.search = '';
    Router.render();
  });
});
